<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_WithFields" Id="{56121de7-72c4-400b-94a3-0223430bf11f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_WithFields
VAR_INPUT
	InField1 	: INT;
	InField2 	: Tc2_System.ST_CpuCoreInfo;
	InField3 	: ARRAY[0..4] OF INT;
END_VAR
VAR_IN_OUT
	InOutField1 : TIME;
END_VAR
VAR_OUTPUT
	{attribute 'hello there' := '42'}
	OutField1 	: __UXINT;
	// This is a comment for OutField2!
	OutField2 	: Tc2_System.E_TcMemoryArea;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <CFC>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="CFCImplementationObject">
              <o n="Items" t="CFCItemList">
                <l2 n="InnerList" />
              </o>
              <n n="ParameterInitializationMethodGenerator" />
              <o n="RoutingPathTable" t="CFCRoutingPathTable">
                <d2 n="InnerDictionary" />
              </o>
              <v n="AutoSizeCanvas">true</v>
              <v n="CanvasWidth">2</v>
              <v n="CanvasHeight">2</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
            <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
            <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
            <Type n="Int32">System.Int32</Type>
          </TypeList>
        </XmlArchive>
      </CFC>
    </Implementation>
  </POU>
</TcPlcObject>